# Generated by Django 5.2.5 on 2025-12-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bodega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("direccion", models.CharField(blank=True, max_length=255)),
                ("ciudad", models.CharField(blank=True, max_length=100)),
                (
                    "capacidad_maxima",
                    models.PositiveIntegerField(
                        help_text="Capacidad máxima en unidades (o en la unidad que maneje el negocio)."
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "bodegas",
                "ordering": ["nombre"],
            },
        ),
    ]
