# Generated by Django 3.2.6 on 2025-09-26 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('cliente', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('transito', 'Transito'), ('alistamiento', 'Alistamiento'), ('por_verificar', 'Por Verificar'), ('rechazado_x_verificar', 'Rechazado x Verificar'), ('verificado', 'Verificado'), ('empacado_x_despacho', 'Empacado x Despacho'), ('despachado', 'Despachado'), ('despachado_x_facturacion', 'Despachado x Facturacion'), ('entregado', 'Entregado'), ('devuelto', 'Devuelto'), ('produccion', 'Produccion'), ('bordado', 'Bordado'), ('dropshipping', 'Dropshipping'), ('compra', 'Compra'), ('anulado', 'Anulado')], default='transito', max_length=40)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('productos', models.ManyToManyField(related_name='pedidos', through='pedidos.DetallePedido', to='productos.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('transito', 'Transito'), ('alistamiento', 'Alistamiento'), ('por_verificar', 'Por Verificar'), ('rechazado_x_verificar', 'Rechazado x Verificar'), ('verificado', 'Verificado'), ('empacado_x_despacho', 'Empacado x Despacho'), ('despachado', 'Despachado'), ('despachado_x_facturacion', 'Despachado x Facturacion'), ('entregado', 'Entregado'), ('devuelto', 'Devuelto'), ('produccion', 'Produccion'), ('bordado', 'Bordado'), ('dropshipping', 'Dropshipping'), ('compra', 'Compra'), ('anulado', 'Anulado')], max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='pedidos.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
    ]
