"""
Django settings for WMSProvesi_pedidos project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6d+1kcj$b2o+ne(he&sq2$@smhk9u1tvz$_2^yr6@jmf#*ws%8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pedidos',
    'productos',
    'corsheaders',
    'rest_framework',
    'social_django',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'WMSProvesi_pedidos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
           	'social_django.context_processors.backends',
    		'social_django.context_processors.login_redirect', 

	   ],
        },
    },
]

WSGI_APPLICATION = 'WMSProvesi_pedidos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'provesi_db',
        'USER': 'provesi_user',
        'PASSWORD': 'isis2503',
        'HOST': '172.31.30.126',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CORS config
CORS_ALLOWED_ORIGINS = [
    "http://3.222.161.109:5173",
]
CORS_ALLOW_CREDENTIALS = True

# REST Framework: usar sesión, NO JWT
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
    ),
}

AUTHENTICATION_BACKENDS = (
    'social_core.backends.auth0.Auth0OAuth2',  # Auth0
    'django.contrib.auth.backends.ModelBackend',  # Django username/password (por si acaso)
)


# URL donde se redirige al iniciar login (Auth0)
LOGIN_URL = '/login/auth0'


# A dónde vuelve Auth0 después de LOGIN exitoso
LOGIN_REDIRECT_URL = '/'   # Puedes dejar / o algo tipo /app/

# A dónde vuelve el usuario después de LOGOUT
LOGOUT_REDIRECT_URL = 'http://3.222.161.109:8080'

# Datos de tu aplicación en Auth0 (tipo Regular Web Application)
SOCIAL_AUTH_AUTH0_DOMAIN = 'dev-dr00hjc2t54h2t44.us.auth0.com'
SOCIAL_AUTH_AUTH0_KEY = '6JUf2CUd9P1gtWrlp24iRwL5aDWbweXi'  # Client ID
SOCIAL_AUTH_AUTH0_SECRET = '-6LYC7J4y2VA0FoEg_BgR-SwQk-ERZqbAASvuiS_HKl-kapaMHRP4ndRc9z4BLhj'           # NO lo compartas
SOCIAL_AUTH_AUTH0_SCOPE = [
    'openid',
    'profile',
    'email',
]
